/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ru.otus;

import com.google.common.collect.Lists;
import java.util.List;
import com.google.common.base.Joiner;

public class HelloOtus {
    public static void main(String... args) {
        List<String> myList = Lists.newArrayList("H", "e", "l", "l", "o", " ", "O",
                "t", "u", "s", "!");

        String result = Joiner.on("").join(myList);

        System.out.println(result);
    }
}
